version: 2
jobs:
  build:
    working_directory: ~/demo_app
    docker:
      # primary docker container; all `steps` will run here.
      - image: crystallang/crystal:0.27.0
        environment:
          DATABASE_URL: postgres://runner:@localhost:5432/skirmish_test

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: runner
          POSTGRES_DB: skirmish_test
          # POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
      - run:
          name: Install dependencies
          command: shards install
      - run:
          name: Install PostgreSQL Client
          command: |
              apt-get update
              apt-get install -y wget
              echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
              wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
              apt-get install -y postgresql-client
      - save_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run:
          name: test
          command: crystal spec
